-- MySQL Script generated by MySQL Workbench
-- Fri Dec 20 17:37:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tcms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcms` DEFAULT CHARACTER SET utf8 ;
USE `tcms` ;

-- -----------------------------------------------------
-- Table `tcms`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`subscription` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `test_case_limit` BIGINT NOT NULL,
  `user_limit` BIGINT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcms`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`tenant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `domain_name` VARCHAR(500) NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `modified_at` DATETIME NULL DEFAULT now(),
  `created_by` BIGINT NULL,
  `modified_by` BIGINT NULL,
  `subscription_id` BIGINT NOT NULL,
  `subscription_ends_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `domain_name_UNIQUE` (`domain_name` ASC) VISIBLE,
  INDEX `subscription_id_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `subscription_id`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `tcms`.`subscription` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcms`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`login_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email_address` NVARCHAR(320) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `password_sha_256` VARCHAR(255) NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `created_by` BIGINT NULL,
  `modified_by` BIGINT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC) VISIBLE,
  INDEX `tenant_id_idx` USING BTREE (`tenant_id`) KEY_BLOCK_SIZE = 10 VISIBLE,
  INDEX `type_id_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `tenant_id`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `tcms`.`tenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `tcms`.`login_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcms`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcms`.`jt_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcms`.`jt_user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `tcms`.`role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `tcms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
